version: "3"

services:
  db:
    build: ./build/db
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - db.env
    # command: --default-authentication-plugin=mysql_native_password
    network_mode: host
  adminer:
    image: adminer:4.8.0
    ports:
      - 8081:8080
  phpmyadmin:
    image: phpmyadmin:5.0.4-apache
    ports:
      - 8080:80
    # environment:
      # - PMA_ARBITRARY=1
  web:
    build: ./build/php
    volumes:
      - .:/var/www/html/
    ports:
      - 80:80
